/**
 * CSTalk 디자인 시스템 (Stitch / design/ECH메인·ECH화면설계 공통 팔레트)
 * — Vanilla CSS는 `styles.css`의 CSS 변수와 동일 토큰을 사용합니다.
 * — `npx tailwindcss` 도입 시 content 경로로 빌드 가능.
 */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './app.js'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#dce4e8',
        'on-surface-variant': '#596064',
        'on-secondary-fixed': '#314055',
        'on-primary': '#fbf7ff',
        'inverse-on-surface': '#9a9d9f',
        'outline-variant': '#acb3b7',
        error: '#a8364b',
        'primary-container': '#6760fd',
        'on-secondary-fixed-variant': '#4d5d73',
        'on-tertiary-fixed-variant': '#003954',
        'surface-dim': '#d4dbdf',
        'inverse-primary': '#8582ff',
        'surface-container': '#eaeff2',
        background: '#f7f9fb',
        'primary-fixed': '#6760fd',
        'on-primary-fixed-variant': '#edeaff',
        'inverse-surface': '#0b0f10',
        'secondary-dim': '#44546a',
        'on-primary-container': '#000000',
        'on-error': '#fff7f7',
        'tertiary-container': '#34b5fa',
        primary: '#4e45e4',
        'tertiary-dim': '#005980',
        'surface-container-high': '#e3e9ed',
        'primary-fixed-dim': '#5a52f0',
        'tertiary-fixed-dim': '#17a8ec',
        secondary: '#506076',
        'surface-container-low': '#f0f4f7',
        'on-tertiary-fixed': '#00121e',
        'secondary-fixed-dim': '#c5d6f0',
        surface: '#f7f9fb',
        outline: '#747c80',
        'on-tertiary-container': '#003047',
        'surface-bright': '#f7f9fb',
        'surface-tint': '#4e45e4',
        'secondary-fixed': '#d3e4fe',
        'on-surface': '#2c3437',
        'on-primary-fixed': '#ffffff',
        'error-dim': '#6b0221',
        tertiary: '#006592',
        'tertiary-fixed': '#34b5fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#dce4e8',
        'secondary-container': '#d3e4fe',
        'on-secondary': '#f7f9ff',
        'on-secondary-container': '#435368',
        'on-error-container': '#6e0523',
        'on-background': '#2c3437',
        'primary-dim': '#4135d8',
        'on-tertiary': '#f5f9ff',
        'error-container': '#f97386',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        ambient:
          '0 32px 64px -12px rgba(44, 52, 55, 0.06), 0 12px 24px -8px rgba(44, 52, 55, 0.04)',
        'ambient-sm': '0 4px 20px rgba(44, 52, 55, 0.06)',
        'ghost-primary': '0 0 0 2px rgba(78, 69, 228, 0.18)',
        'tertiary-glow': '0 0 0 2px rgba(255,255,255,0.9), 0 0 10px 2px rgba(0, 101, 146, 0.35)',
      },
      fontSize: {
        'headline-lg': ['1.5rem', { lineHeight: '1.25', letterSpacing: '-0.02em' }],
        'headline-md': ['1.25rem', { lineHeight: '1.3', letterSpacing: '-0.02em' }],
        'label-sm': ['0.6875rem', { lineHeight: '1.2', letterSpacing: '0.05em' }],
      },
      fontFamily: {
        headline: ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
