package com.ech.backend.domain.audit;

public enum AuditEventType {

    // 채널 이벤트
    CHANNEL_CREATED,
    CHANNEL_JOINED,
    CHANNEL_MEMBER_REMOVED,

    // 메시지 이벤트 (본문 미기록, 메타데이터만)
    MESSAGE_SENT,
    MESSAGE_REPLY_SENT,

    // 파일 이벤트
    FILE_UPLOADED,
    FILE_DOWNLOAD_INFO_ACCESSED,
    CHANNEL_LIBRARY_FOLDER_CREATED,
    CHANNEL_LIBRARY_FOLDER_UPDATED,
    CHANNEL_LIBRARY_FOLDER_DELETED,
    CHANNEL_FILE_LIBRARY_UPDATED,

    // 업무 항목 이벤트
    WORK_ITEM_CREATED,

    // 캘린더 이벤트
    CALENDAR_EVENT_CREATED,
    CALENDAR_EVENT_UPDATED,
    CALENDAR_EVENT_DELETED,
    CALENDAR_SHARE_CREATED,
    CALENDAR_SHARE_ACCEPTED,
    CALENDAR_SHARE_DECLINED,
    CALENDAR_SUGGESTION_CREATED,
    CALENDAR_SUGGESTION_CONFIRMED,
    CALENDAR_SUGGESTION_DISMISSED,

    // 칸반 이벤트
    KANBAN_BOARD_CREATED,
    KANBAN_COLUMN_CREATED,
    KANBAN_COLUMN_UPDATED,
    KANBAN_COLUMN_DELETED,
    KANBAN_CARD_CREATED,
    KANBAN_CARD_UPDATED,
    KANBAN_CARD_MOVED,
    KANBAN_CARD_STATUS_CHANGED,
    KANBAN_CARD_DELETED,
    KANBAN_ASSIGNEE_ADDED,
    KANBAN_ASSIGNEE_REMOVED,

    // 조직/사용자 관리 이벤트
    ORG_SYNC_EXECUTED,
    USER_STATUS_CHANGED,

    // 보존 정책 / 아카이빙 이벤트
    RETENTION_POLICY_UPDATED,
    DATA_ARCHIVED,

    // 배포 관리 이벤트
    RELEASE_UPLOADED,
    RELEASE_ACTIVATED,
    RELEASE_ROLLED_BACK,
    RELEASE_DELETED,

    // AI 게이트웨이 (프롬프트 원문 미저장·메타만)
    AI_GATEWAY_POLICY_BLOCKED,
    AI_GATEWAY_PROVIDER_NOT_CONFIGURED
}
